# Dependencies
markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true
  input: GFM

permalink: pretty
source: docs
baseurl: /custom-elements

github:
  repo: https://github.com/mdo/custom-elements
